version: '3.3'

services: 
  mysql-nubicall:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=users
      - MYSQL_USER=nubicall
      - MYSQL_PASSWORD=Nub1c@ll
  users-nubicall:
    image: mdwarg/users
    depends_on:
      - mysql-nubicall
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-nubicall
      - DATABASE_USER=nubicall
      - DATABASE_PASSWORD=Nub1c@ll
      - DATABASE_NAME=users
      - DATABASE_PORT=3306